# Generated by Django 2.2.4 on 2019-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=30)),
                ('cat_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=5)),
                ('c_title', models.CharField(max_length=30)),
                ('c_detail', models.CharField(max_length=100)),
                ('c_state', models.CharField(max_length=20)),
                ('c_city', models.CharField(max_length=30)),
                ('c_fulladdress', models.CharField(max_length=30)),
                ('c_area', models.CharField(max_length=30)),
                ('c_pin', models.IntegerField(max_length=7)),
                ('c_landmark', models.CharField(max_length=30)),
                ('c_date', models.CharField(max_length=10)),
                ('c_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=5)),
                ('f_text', models.CharField(max_length=50)),
                ('f_date', models.CharField(max_length=10)),
                ('f_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=5)),
                ('m_name', models.CharField(max_length=30)),
                ('m_mobile', models.IntegerField(max_length=10)),
                ('m_password', models.CharField(max_length=30)),
                ('m_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=5)),
                ('u_name', models.CharField(max_length=30)),
                ('u_email', models.CharField(max_length=30)),
                ('u_mobile', models.IntegerField(max_length=10)),
                ('u_password', models.CharField(max_length=30)),
                ('u_state', models.CharField(max_length=30)),
                ('u_city', models.CharField(max_length=30)),
                ('u_fulladdress', models.CharField(max_length=30)),
                ('u_area', models.CharField(max_length=30)),
                ('u_pin', models.IntegerField(max_length=7)),
                ('u_landmark', models.CharField(max_length=30)),
            ],
        ),
    ]
