# Generated by Django 2.2.4 on 2019-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_fulladdress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_landmark',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_state',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='c_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='m_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_pin',
            field=models.IntegerField(default=0),
        ),
    ]
