# Generated by Django 2.2.4 on 2019-08-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20190825_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='c_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='c_state',
            field=models.CharField(max_length=30),
        ),
    ]
