# Generated by Django 2.2.4 on 2019-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20190827_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_password1',
            field=models.CharField(default=123456789, max_length=30),
            preserve_default=False,
        ),
    ]
