# Generated by Django 2.2.4 on 2019-09-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20190902_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='f_text',
            field=models.CharField(max_length=1000),
        ),
    ]
