# Generated by Django 2.2.5 on 2019-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20190911_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='c_photo1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='c_photo2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
