# Generated by Django 2.2.5 on 2019-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20190918_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='c_photo1',
            field=models.FileField(upload_to='images/'),
        ),
    ]
